### ISSUE TITLE
accéder aux noeuds

### ISSUE THREAD

**Issue by mencattini** [cui-unige/decision-diagrams-mencattini#1]
Hello,

Comment fait-on pour accéder aux successeurs dans ta structure?

J'ai essayé:
```lua
      Fun.frommap(dd.nodes):each(function(_,n)
        print("n = ",n)
      end)
```
et 
```lua
Fun.fromtable(dd.nodes):each(function(n)
   print("n = ",n)
end)
```

Et j'ai des erreurs dans le test:
```bash
Error → src/dd/init_spec.lua @ 14
decision diagrams #test can create dd from mapping
/usr/share/lua/5.3/fun.lua:98: invalid iterator
```
dans les deux cas

Merci d'avance

**Comment by saucisson** [comment]
Pour accéder aux successeurs d'un noeud `n`: `n [true]` et `n[false]`.
`dd.nodes` est une collection de l'ensemble des noeuds existants.

**Comment by mencattini** [comment]
Mais mon itérateur n'est pas valide. Ce que j'ai écris en dessus ne me permet pas d'itérer sur les successeurs.

**Comment by saucisson** [comment]
```lua
local n = Dd.create { ... }
local succ1 = n [true]
local succ2 = n [false]
```

Normalement ça, ça fonctionne. Pas besoin d'itérateur sur les successeurs, on est en BDD et un noeud n'a donc que deux successeurs, par les valeurs `true` et `false`.

**Comment by mencattini** [comment]
D'accord, je comprend mieux.
Au niveau du retour de la fonction `DD.dontcare`; je vois pas trop ce qu'on doit renvoyer.

**Comment by mencattini** [comment]
Ah c'est bon j'ai trouvé en fait.
Merci
