### ISSUE TITLE
Erreur durant wercker build

### ISSUE THREAD

**Issue by mencattini** [cui-unige/decision-diagrams-mencattini#3]
Hello,

J'ai écrit tout les parties du code manquantes dans le fichier `init.lua`. Et lorsque que je lance avec `busted`, j'ai 15 tests qui se lancent et qui passent (ce qui est le bon nombre).
Lorsque j'utilise `wercker build`, il a beaucoup de print de debeug qui ne sont pas de moi, et à la fin il y a une erreur dans les tests sur les `petrinets` alors que c'est une partie que je n'ai pas changé.
```bash
Failure -> src/dd/petrinet_spec.lua @ 33
dds can generate the state space of Petri nets for #page92
src/dd/petrinet_spec.lua:37: Expected objects to be equal.
Passed in:
(number) 4
Expected:
(number) 3

stack traceback:
	src/dd/petrinet_spec.lua:37: in function <src/dd/petrinet_spec.lua:33>
```

Merci d'avance

**Comment by saucisson** [comment]
Petite question : regardons les deux sorties (dans et hors wrecker).
Dans wrecker:
```
p4=true p3=true p2=false p1=false -> true
p4=false p3=true p2=* p1=false -> true
p4=false p3=false p2=* p1=true -> true
```

Hors wrecker:
```
p2=true p1=true p4=false p3=false -> true
p2=true p1=false p4=false p3=true -> true
p2=false p1=true p4=false p3=false -> true
p2=false p1=false p4=* p3=true -> true
``

Qu'observes-tu ?

**Comment by mencattini** [comment]
Pas grand chose.
L'output complet est monstrueux, et à part l'erreur, je vois pas trop ce que je dois observer.

**Comment by saucisson** [comment]
L'ordre des variables n'est pas le même. Je t'ai donné ici les deux sorties intéressantes pour ce test qui fail. Tu peux dédoubler les chemins avec des `*` (qui correspond au don't care) et comparer les deux variantes.

**Comment by mencattini** [comment]
Mais du coup, c'est à cause de mon implémentation que le test de petrinet plante?

**Comment by saucisson** [comment]
Je répondrai une fois que tu auras comparé les chemins.

**Comment by mencattini** [comment]
Ce que je vois c'est que `hors wercker contient ` strictement tout les états de `dans wercker`.

Il y a `p2=true p1=false p4=false p3=true -> true` qui n'est pas dans le `dans wercker`.
